name: "Checkout Repository and Setup Node"
description: "Checks out the repo and installs Node"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Setup node
      uses: actions/setup-node@v6
      with:
        node-version-file: ".nvmrc"
