---
gate_policy:
  newIssues:
    maxNewIssues: 10
    issueSeverityThreshold: "Medium"
  maxAllowedSecurityIssues: 10
  maxComplexity: 20
  maxDuplicatedBlocks: 10
  minCoverageVariationPercent: -25
  minDiffCoveragePercent: 70
exclude_paths:
  - "/github/**"
  - "/.hooks/**"
  - "/.idea/**"
  - "/.mvn/**"
  - "/flowable-engine/src/test/**"
  - "/gateway/src/test/**"
  - "/mysql-timestamp-to-datetime/src/test/**"
  - "/oauth2-authorization-server/src/test/**"
  - "/oauth2-authorization-server-opaque/src/test/**"
  - "/oauth2-autoconfig/src/test/**"
  - "/oauth2-gateway-mvc/src/test/**"
  - "/spring-security/src/test/**"
  - "/spring-security-opaque/src/test/**"
  - "/test-controller-autoconfig/src/test/**"
  - ".gitattributes"
  - ".gitignore"
  - ".gitmodules"
  - ".prettierrc"
  - "CONTRIBUTING.md"
  - "LICENSE"
  - "lombok.config"
  - "mvnw"
  - "mvnw.cmd"
  - "README.md"
