---
gate_policy:
  newIssues:
    maxNewIssues: 0
    issueSeverityThreshold: "Medium"
  maxAllowedSecurityIssues: 0
  maxComplexity: 20
  maxDuplicatedBlocks: 1
  minCoverageVariationPercent: -25
  minDiffCoveragePercent: 70
exclude_paths:
  - "./github/**"
  - "./.hooks/**"
  - "./.idea/**"
  - "./.mvn/**"
  - ".gitattributes"
  - ".gitignore"
  - ".gitmodules"
  - ".prettierrc"
  - "CONTRIBUTING.md"
  - "LICENSE"
  - "lombok.config"
  - "mvnw"
  - "mvnw.cmd"
  - "README.md"
