spring:
  application:
    name: todo-service
  jpa:
    hibernate:
      ddl-auto: validate
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5433/todo_db
    username: myuser
    password: secret
server:
  port: 6958
