name: "Setup Node and Java"
description: "Installs Node and Java"

runs:
  using: "composite"
  steps:
    - name: Setup node
      uses: ./.github/actions/setup-node

    - name: Setup java
      uses: ./.github/actions/setup-java
