ALTER TABLE TEST_ENTITY_CALENDAR MODIFY COLUMN DATA TEXT;

ALTER TABLE TEST_ENTITY_DATE MODIFY COLUMN DATA TEXT;

ALTER TABLE TEST_ENTITY_OFFSET_DATE_TIME MODIFY COLUMN DATA TEXT;

ALTER TABLE TEST_ENTITY_TIMESTAMP MODIFY COLUMN DATA TEXT;

ALTER TABLE TEST_ENTITY_ZONED_DATE_TIME MODIFY COLUMN DATA TEXT;
