spring:
  application:
    name: todo-service
  jpa:
    hibernate:
      ddl-auto: validate
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgres://localhost:5432/todo_db
    username: myuser
    password: secret
