spring:
  application:
    name: spring-security-opaque
  threads:
    virtual:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - mappings
---
spring:
  config:
    activate:
      on-profile: local
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: spring-security-opaque-client
          client-secret: spring-security-opaque-secret
server:
  port: 9055
logging:
  level:
    com.mrlonis.example.security: debug
