spring:
  application:
    name: oauth2-server
  liquibase:
    enabled: false
  threads:
    virtual:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - mappings
application:
  clients:
    oidc:
      client-id: oidc-client
      client-secret: "{noop}oidc-secret"
      client-authentication-method: none
      authorization-grant-type: authorization_code
      redirect-uris:
        - /login/oauth2/code/oidc-client
      post-logout-redirect-uri: /
      scopes:
        - openid
        - profile
        - email
      client-settings:
        require-authorization-consent: false
    gateway:
      client-id: gateway-client
      client-secret: "{noop}gateway-secret"
      client-authentication-method: client_secret_basic
      authorization-grant-type: client_credentials
      redirect-uris:
        - /login/oauth2/code/gateway-client
      post-logout-redirect-uri: /
      scopes:
        - gateway
      client-settings:
        require-authorization-consent: false
    postman:
      client-id: postman-public-client
      client-authentication-method: none
      authorization-grant-type: authorization_code
      redirect-uris:
        - https://oauth.pstmn.io/v1/callback
        - /login/oauth2/code/postman-public-client
      scopes:
        - openid
        - profile
        - email
      client-settings:
        require-authorization-consent: true
        require-proof-key: true
    test:
      client-id: test-public-client
      client-authentication-method: none
      authorization-grant-type: authorization_code
      redirect-uris:
        - /login/oauth2/code/test-public-client
      scopes:
        - openid
        - profile
        - email
      client-settings:
        require-proof-key: true
    spring-security:
      client-id: spring-security-client
      client-secret: "{noop}spring-security-secret"
      client-authentication-method: client_secret_basic
      authorization-grant-type: client_credentials
      redirect-uris:
        - /login/oauth2/code/spring-security-client
      post-logout-redirect-uri: /
      scopes:
        - spring-security
      client-settings:
        require-authorization-consent: false
---
spring:
  config:
    activate:
      on-profile: local
server:
  port: 9562
logging:
  level:
    com.mrlonis.example.oauth2: debug
