server:
  reactive:
    session:
      cookie:
        same-site: none
        http-only: false
        secure: false
        name: CUSTOM-SESSION-NAME
spring:
  application:
    name: oauth2-gateway-mvc
  session:
    redis:
      save-mode: always
  threads:
    virtual:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - mappings
---
spring:
  config:
    activate:
      on-profile: ssl-redis
  data:
    redis:
      ssl:
        enabled: true
  session:
    redis:
      save-mode: always
---
spring:
  config:
    activate:
      on-profile: local
server:
  port: 9203
logging:
  level:
    com.mrlonis.example.gateway: debug
    org.springframework.security: debug
    root: debug
