CREATE TABLE TEST_ENTITY_CALENDAR (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  TYPE CHAR(4) NOT NULL,
  CODE CHAR(4),
  DATA VARCHAR(10000),
  CREATED_DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATED_USER VARCHAR(8) NOT NULL,
  UPDATED_DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UPDATED_USER VARCHAR(8) NOT NULL
);

CREATE TABLE TEST_ENTITY_DATE (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  TYPE CHAR(4) NOT NULL,
  CODE CHAR(4),
  DATA VARCHAR(10000),
  CREATED_DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATED_USER VARCHAR(8) NOT NULL,
  UPDATED_DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UPDATED_USER VARCHAR(8) NOT NULL
);

CREATE TABLE TEST_ENTITY_OFFSET_DATE_TIME (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  TYPE CHAR(4) NOT NULL,
  CODE CHAR(4),
  DATA VARCHAR(10000),
  CREATED_DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATED_USER VARCHAR(8) NOT NULL,
  UPDATED_DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UPDATED_USER VARCHAR(8) NOT NULL
);

CREATE TABLE TEST_ENTITY_TIMESTAMP (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  TYPE CHAR(4) NOT NULL,
  CODE CHAR(4),
  DATA VARCHAR(10000),
  CREATED_DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATED_USER VARCHAR(8) NOT NULL,
  UPDATED_DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UPDATED_USER VARCHAR(8) NOT NULL
);

CREATE TABLE TEST_ENTITY_ZONED_DATE_TIME (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  TYPE CHAR(4) NOT NULL,
  CODE CHAR(4),
  DATA VARCHAR(10000),
  CREATED_DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATED_USER VARCHAR(8) NOT NULL,
  UPDATED_DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UPDATED_USER VARCHAR(8) NOT NULL
);
