spring:
  application:
    name: spring-security
  threads:
    virtual:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - mappings
---
spring:
  config:
    activate:
      on-profile: local
server:
  port: 6059
logging:
  level:
    com.mrlonis: debug
